FROM python:3.11-slim as app
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY main.py auth.py 

FROM nginx:1.27-alpine as proxy
COPY nginx/default.conf /etc/nginx/nginx.conf

FROM python:3.11-slim
WORKDIR /app
# bring in app env
COPY --from=app /usr/local/lib/python3.11 /usr/local/lib/python3.11
COPY --from=app /usr/local/bin /usr/local/bin
COPY --from=app /app /app
# add nginx
COPY --from=proxy /etc/nginx/nginx.conf /etc/nginx/nginx.conf
EXPOSE 8080
# run both processes (simple)
CMD sh -c "nginx & uvicorn main:app --host 0.0.0.0 --port 8000"
